server:
  port: 6060

swagger.enabled: true

spring:
  data:
    mongodb:
   #   host: 47.93.1.51
   #   port: 27017
   #   database: admin
      uri: mongodb://47.93.1.51:27017/admin

  jpa:
    repositories:
      enabled: true
    show-sql: true
